apiVersion: v1
kind: Service
metadata:
  name: service-USER_ID_PLACEHOLDER
  labels:
    user-id: USER_ID_PLACEHOLDER
spec:
  type: NodePort
  selector:
    app: app-USER_ID_PLACEHOLDER
  ports:
    - name: jupyter
      port: 8888
      targetPort: 8888
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: minio-api
      port: 9000
      targetPort: 9000
    - name: minio-ui
      port: 9001
      targetPort: 9001
    - name: influxdb
      port: 8086
      targetPort: 8086
    - name: grafana
      port: 3000
      targetPort: 3000

