apiVersion: v1
kind: Service
metadata:
  name: service-USER_ID_PLACEHOLDER
  labels:
    user-id: USER_ID_PLACEHOLDER
spec:
  type: NodePort
  selector:
    app: app-USER_ID_PLACEHOLDER
  ports:
    - name: influxdb
      port: 8086
      targetPort: 8086
    - name: grafana
      port: 3000
      targetPort: 3000

