apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-pvc-placeholder
  labels:
    user-id: user-id-placeholder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi