apiVersion: v1
kind: Service
metadata:
  name: svc-USER_ID_PLACEHOLDER-minio
  labels:
    user-id: USER_ID_PLACEHOLDER
spec:
  type: NodePort
  selector:
    app: app-USER_ID_PLACEHOLDER
  ports:
    - name: minio-ui
      port: 9001
      targetPort: 9001
    - name: minio-api
      port: 9000
      targetPort: 9000