# 共有MinIOサーバーに外部からアクセスするためのドア（ポート）を開けます。
apiVersion: v1
kind: Service
metadata:
  name: public-minio-service
spec:
  type: NodePort
  selector:
    app: public-minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001

