# 共有MinIOサーバー本体のコンテナを起動するための設計図です。
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-minio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-minio
  template:
    metadata:
      labels:
        app: public-minio
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: public-minio-pvc
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1001:1001 /data"]
        volumeMounts:
        - name: storage
          mountPath: /data
      containers:
      - name: minio
        image: minio/minio:latest
        command: ["minio", "server", "/data", "--console-address", ":9001"]
        ports:
        - { containerPort: 9000, name: api }
        - { containerPort: 9001, name: console }
        env:
        - { name: MINIO_ROOT_USER, value: "minioadmin" }
        - { name: MINIO_ROOT_PASSWORD, value: "minioadmin" }
        volumeMounts:
        - { name: storage, mountPath: /data }
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001

